schema_version = "1.0.0"

id = "no_rotation"
version = "1.0.0"
name = "Disable Object Rotation"
tagline = "This extension enforces a (0, 0, 0) euler rotation on all objects"
maintainer = "ChaoticByte <contact@chaoticbyte.net>"
type = "add-on"

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
